# fly.toml app configuration file generated for server-summer-frost-6796 on 2024-10-01T19:33:01-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-wandering-moon-943'
primary_region = 'mia'

[build]

[mounts]
source = "db_volume"
destination = "/data"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
