// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AdminHome() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"container mx-auto px-6 py-8\"><h2 class=\"text-3xl font-semibold text-gray-800 mb-6\">Dashboard</h2><!-- Stats Grid --><div class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8\"><div class=\"bg-white rounded-lg shadow-md p-6\"><h3 class=\"text-lg font-semibold mb-2\">Total Users</h3><p class=\"text-3xl font-bold\">1,234</p></div><div class=\"bg-white rounded-lg shadow-md p-6\"><h3 class=\"text-lg font-semibold mb-2\">New Users</h3><p class=\"text-3xl font-bold\">12</p></div><div class=\"bg-white rounded-lg shadow-md p-6\"><h3 class=\"text-lg font-semibold mb-2\">Jobs Pending</h3><p class=\"text-3xl font-bold\">23</p></div><div class=\"bg-white rounded-lg shadow-md p-6\"><h3 class=\"text-lg font-semibold mb-2\">Jobs Completed</h3><p class=\"text-3xl font-bold\">12,345</p></div></div><!-- Recent Activity --><div class=\"bg-white rounded-lg shadow-md p-6\"><h3 class=\"text-xl font-semibold mb-4\">Recent Activity</h3><ul class=\"divide-y divide-gray-200\"><li class=\"py-3\">User John Doe registered</li><li class=\"py-3\">New order #1234 received</li><li class=\"py-3\">User Jane Smith updated their profile</li><li class=\"py-3\">Product \"Awesome Gadget\" added to inventory</li><li class=\"py-3\">Support ticket #5678 closed</li></ul></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
