// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func CreateJobForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form method=\"POST\" hx-post=\"/admin/jobs/new\" hx-trigger=\"submit\" hx-swap=\"afterend\" hx-on::after-request=\"this.reset()\" class=\"mt-5 shadow-sm shadow-stone-300 p-10 rounded-lg\"><p class=\"font-bold text-3xl p-6\">Create Job</p><div class=\"flex flex-col gap-2\"><label form=\"customer_id\" class=\"font-semibold text-lg\">Customer ID</label> <input class=\"border border-black p-2 rounded-md\" id=\"id\" name=\"id\" type=\"number\" min=\"1\" required></div><div class=\"flex flex-col gap-2\"><label for=\"invoice\" class=\"font-semibold text-lg\">Invoice</label> <input class=\"border border-stone-500 p-2 rounded-md\" id=\"invoice\" name=\"invoice\" type=\"text\" placeholder=\"40838\" required></div><div class=\"flex flex-col gap-2\"><label for=\"install_date\" class=\"font-semibold text-lg\">Install Date</label> <input type=\"date\" id=\"install_date\" name=\"install_date\" class=\"border border-stone-500 p-2 rounded-md\"></div><button type=\"submit\" class=\"mt-10 font-semibold text-center p-2 px-3 rounded-md bg-zinc-900 text-white flex items-center space-x-2\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"lucide lucide-package-plus\"><path d=\"M16 16h6\"></path> <path d=\"M19 13v6\"></path> <path d=\"M21 10V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l2-1.14\"></path> <path d=\"m7.5 4.27 9 5.15\"></path> <polyline points=\"3.29 7 12 12 20.71 7\"></polyline> <line x1=\"12\" x2=\"12\" y1=\"22\" y2=\"12\"></line></svg><p>Create Job</p></button></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
